### ISSUE TITLE
util.py calls for an outside dictionary

### ISSUE THREAD

**Issue by ace510** [mikeyy/omeglebot#2]
when I try to run omeglebot it tries to connect to a dictionary sourced from usr/share/dict/words it would help if we could roll that dict into the library itself, or add some code that wgets that dict if it doesn't exist

**Comment by mikeyy** [comment]
Thanks for reporting this, let me know if it works for you now

**Comment by ace510** [comment]
dank, hate to be the queaky wheel, but I need this thing to run before I can develop it

**Comment by mikeyy** [comment]
No worries, I'm more than welcome the reporting. Interested what you have in mind of developing.
